# Generated by Django 6.0.1 on 2026-02-18 09:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_admin_leaderboard_oppcategory_student_linkedin_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opportunity',
            name='city',
        ),
        migrations.RemoveField(
            model_name='opportunity',
            name='region',
        ),
        migrations.RemoveField(
            model_name='student',
            name='visibility',
        ),
    ]
