# Generated by Django 6.0.1 on 2026-02-19 08:08

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_remove_opportunity_city_remove_opportunity_region_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opportunity',
            name='description_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description_html',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='description_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='opportunity',
            name='last_checked_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='OpportunityVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fetched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('source_link', models.CharField(blank=True, max_length=800, null=True)),
                ('http_status', models.IntegerField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True, null=True)),
                ('description_text', models.TextField(blank=True, null=True)),
                ('content_hash', models.CharField(blank=True, db_index=True, max_length=64, null=True)),
                ('changed', models.BooleanField(default=False)),
                ('opportunity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='accounts.opportunity')),
            ],
        ),
    ]
