# Generated by Django 6.0.1 on 2026-02-19 09:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_opportunity_description_hash_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='submitted_by_id',
        ),
        migrations.AlterField(
            model_name='submission',
            name='submitted_by_type',
            field=models.CharField(blank=True, choices=[('student', 'Student'), ('admin', 'Admin'), ('ai', 'AI')], help_text='Auto-set based on submitted_by_student/submitted_by_admin', max_length=20, null=True),
        ),
    ]
